angular.module('partials', [])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/base.html', [
'',
'<div class="row">',
'  <div class="col-md-11">',
'    <h1>Patissier</h1>',
'  </div>',
'  <div class="col-md-1">',
'    <p><a ui-sref="monthly_progress" class="glyphicon glyphicon-align-left gi-1-5x"></a></p>',
'  </div>',
'</div>',
'<hr>',
'<div class="row">',
'  <div ui-view="nav" class="col-md-2 main-nav"></div>',
'  <div ui-view class="col-md-10 main-main"></div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/dashboard.html', [
'',
'<div>',
'  <h2>dashboard</h2>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/img_modal.html', [
'',
'<div class="modal-header"><img src="{{img|home}}" style="width: 568px">',
'  <div class="modal-footer">',
'    <button ng-click="cancel()" class="btn btn-warning">Close</button>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/monthly_progress.html', [
'',
'<div id="report"> ',
'  <h3>Progress for month: ',
'    <select ng-model="current_month" ng-options="b as b for b in dates">',
'      <option value="">all</option>',
'    </select>',
'  </h3>',
'  <div ng-repeat="catData in data" class="chart">',
'    <div class="group group-{{catData.type._id}}">',
'      <div ng-repeat="item in catData.recipes" class="row">',
'        <div class="col-md-3 data-header">{{item.recipe}}</div>',
'        <div class="col-md-9 data data-with-{{item.count}}">{{item.count}}</div>',
'      </div>',
'    </div>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/nav.html', [
'',
'<ul class="nav nav-pills small">',
'  <li ng-repeat="type in types" ng-class="{\'active\': current_type._id == type._id}"><a ui-sref="type_detail({typeId: type._id})">{{type.name}}</a></li>',
'</ul>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/recipe_detail.html', [
'',
'<h3>{{recipe.name}}',
'  <button ng-click="addTest()" class="btn btn-default">Add</button>',
'  <button ng-click="openRecipeNotes()" class="btn btn-info">Final Recipe</button>',
'</h3>',
'<div id="tests_list">',
'  <div ng-repeat="test in tests" class="row">',
'    <hr>',
'    <div class="col-md-2">',
'      <div class="media-left"><a href="#" ng-click="changeTest(test)" class="media-left"><span class="badge badge-2x">{{ tests.length - $index }}</span></a></div>',
'      <div class="media-body">',
'        <h4>{{test.date|date:"dd/MM/yyyy"}}</h4>',
'        <star-rating ng-model="test.rating" readonly="true" size="&quot;xxs&quot;"></star-rating>',
'        <div ng-show="test.img" class="row img">',
'          <div class="thumbnail"><img src="{{test.img|home}}" ng-click="openImage(test.img)"></div>',
'        </div>',
'      </div>',
'    </div>',
'    <div class="col-md-10">',
'      <table width="100%" class="table table-bordered">',
'        <tbody>',
'          <tr>',
'            <td width="10%">Aspect</td>',
'            <td width="45%">{{test.aspect_obs}}</td>',
'            <td width="45%">{{test.aspect_corr}}</td>',
'          </tr>',
'          <tr>',
'            <td>Smell</td>',
'            <td>{{test.smell_obs}}</td>',
'            <td>{{test.smell_corr}}</td>',
'          </tr>',
'          <tr>',
'            <td>Taste</td>',
'            <td>{{test.taste_obs}}</td>',
'            <td>{{test.taste_corr}}</td>',
'          </tr>',
'          <tr>',
'            <td>Texture</td>',
'            <td>{{test.texture_obs}}</td>',
'            <td>{{test.texture_corr}}</td>',
'          </tr>',
'        </tbody>',
'      </table>',
'      <div ng-if="test.notes">',
'        <h4>Notes</h4>',
'        <p ng-bind-html="renderHtml(test.notes)"></p>',
'      </div>',
'    </div>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/recipe_notes_modal.html', [
'',
'<div class="modal-header">',
'  <div class="row">',
'    <div class="col-md-11">',
'      <h3 class="modal-title">{{recipe.name}}</h3>',
'    </div>',
'    <div class="col-md-1"><a href="#" ng-click="changeEdit(true)" ng-show="!edit" class="glyphicon glyphicon-edit gi-1-5x"><a href="#" ng-click="changeEdit(false)" ng-show="edit" class="glyphicon glyphicon-check gi-1-5x"></a></a></div>',
'  </div> ',
'  <form id="test-form" class="modal-body">',
'    <div ng-show="!edit" class="no-edit">',
'      <div class="row row1">',
'        <div class="col-md-4">',
'          <h4>Ingredients</h4>',
'          <div ng-bind-html="recipe.ingredients"></div>',
'        </div>',
'        <div class="col-md-8">',
'          <h4>Procedure</h4>',
'          <div ng-bind-html="recipe.procedure"></div>',
'        </div>',
'      </div>',
'      <div class="row form-group">',
'        <div class="col-md-4">',
'          <h4>Cooking Time</h4>',
'          <div ng-bind-html="recipe.cooking_time"></div>',
'        </div>',
'        <div class="col-md-8">',
'          <h4>Materials</h4>',
'          <div ng-bind-html="recipe.materials"></div>',
'        </div>',
'      </div>',
'    </div>',
'    <div ng-show="edit" class="form-group">',
'      <notes-form ng-model="recipe"></notes-form>',
'    </div>',
'  </form>        ',
'  <div class="modal-footer">',
'    <button ng-click="close()" ng-class="{\'disabled\': saveInProgress &amp;&amp; typing}" class="btn btn-warning">Close</button>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/test_modal.html', [
'',
'<div class="modal-header">',
'  <h3 class="modal-title">{{add ? \'New \' : \'Change\'}} {{recipe.name}}</h3> ',
'  <form id="test-form" class="modal-body">',
'    <ul class="nav nav-tabs">',
'      <li ng-class="{\'active\': activeTab == \'general\'}"><a href="#" ng-click="changeTab(\'general\')">General</a></li>',
'      <li ng-class="{\'active\': activeTab == \'notes\'}"><a href="#" ng-click="changeTab(\'notes\')">Notes</a></li>',
'    </ul><br>',
'    <div ng-show="activeTab == \'general\'" class="form-group">',
'      <p class="input-group">',
'        <input type="text" placeholder="Date" datepicker-popup="dd/MM/yyyy" ng-model="test.date" is-open="opened" close-text="Close" class="form-control"><span class="input-group-btn">',
'          <button type="button" ng-click="openCalendar($event)" value="calendar" class="btn btn-default"><i class="glyphicon glyphicon-calendar"></i></button></span>',
'      </p>',
'      <p class="input-group">',
'        <star-rating ng-model="test.rating" size="&quot;xs&quot;"></star-rating>',
'      </p>',
'      <p class="input-group">',
'        <div>',
'          <h3>{{test.img ? \'Change Photo\' : \'Add Photo\'}}</h3>',
'          <div ng-show="test.temp_img" class="row">',
'            <div class="col-xs-6 col-md-3 thumbnail"><img src="{{test.temp_img}}"></div>',
'          </div>',
'          <input type="file" ng-model="test.temp_img">',
'        </div>',
'      </p>',
'    </div>',
'    <div ng-show="activeTab == \'notes\'" class="form-group">',
'      <p>',
'        <textarea ng-model="test.notes" rows="4" placeholder="Notes" class="form-control"></textarea>',
'      </p>',
'      <div>',
'        <table class="table table-bordered">',
'          <thead>',
'            <tr>',
'              <th>&nbsp;</th>',
'              <th>Observations</th>',
'              <th>Corrections</th>',
'            </tr>',
'          </thead>',
'          <tbody>',
'            <tr>',
'              <td>Aspect</td>',
'              <td>',
'                <textarea ng-model="test.aspect_obs" rows="2" class="form-control"></textarea>',
'              </td>',
'              <td>',
'                <textarea ng-model="test.aspect_corr" rows="2" class="form-control"></textarea>',
'              </td>',
'            </tr>',
'            <tr>',
'              <td>Smell</td>',
'              <td>',
'                <textarea ng-model="test.smell_obs" rows="2" class="form-control"></textarea>',
'              </td>',
'              <td>',
'                <textarea ng-model="test.smell_corr" rows="2" class="form-control"></textarea>',
'              </td>',
'            </tr>',
'            <tr>',
'              <td>Taste</td>',
'              <td>',
'                <textarea ng-model="test.taste_obs" rows="2" class="form-control"></textarea>',
'              </td>',
'              <td>',
'                <textarea ng-model="test.taste_corr" rows="2" class="form-control"></textarea>',
'              </td>',
'            </tr>',
'            <tr>',
'              <td>Texture</td>',
'              <td>',
'                <textarea ng-model="test.texture_obs" rows="2" class="form-control"></textarea>',
'              </td>',
'              <td>',
'                <textarea ng-model="test.texture_corr" rows="2" class="form-control"></textarea>',
'              </td>',
'            </tr>',
'          </tbody>',
'        </table>',
'      </div>',
'    </div>',
'  </form>        ',
'  <div class="modal-footer">',
'    <button ng-click="save()" class="btn btn-primary">Save</button>            ',
'    <button ng-click="cancel()" class="btn btn-warning">Cancel</button>',
'    <button ng-really-message="Are you sure you want to delete this test?" ng-really-click="delete()" ng-if="!add" class="btn btn-danger pull-left">Delete</button>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/type_detail.html', [
'',
'<div>',
'  <div ng-repeat="data in recipes" class="row recipes">',
'    <h4>{{data.group}}</h4>',
'    <div ng-repeat="recipe in data.recipes" class="inner col-md-4"><a ui-sref="recipe_detail({typeId:recipe.type, recipeId:recipe._id})">',
'        <h4>{{recipe.name}}</h4></a>',
'      <div class="row">',
'        <div class="col-md-2">',
'          <div class="number-circle">{{recipe.stats.count}}</div>',
'          <p>times</p>',
'        </div>',
'        <div class="col-md-1"><i ng-if="recipe.stats.count &gt; 0" class="small">last</i></div>',
'        <div class="col-md-6">',
'          <div ng-if="recipe.stats.count &gt; 0">',
'            <star-rating ng-model="recipe.stats.lastTest.rating" readonly="true"></star-rating>',
'            <p>{{recipe.stats.lastTest.date|date:"dd/MM/yyyy"}}</p>',
'          </div>',
'        </div>',
'        <div class="col-md-3 avRating">',
'          <div ng-if="recipe.stats.count &gt; 0">',
'            <div class="number-circle number-circle-small">{{recipe.stats.avRating}}/5</div>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/notes_form.html', [
'',
'<div class="row">',
'  <div class="col-md-4">',
'    <h4>Ingredients</h4>',
'    <text-angular ng-model="model.ingredients" ta-toolbar="[[\'bold\',\'italics\',\'underline\']]"></text-angular>',
'  </div>',
'  <div class="col-md-8">',
'    <h4>Procedure</h4>',
'    <text-angular ng-model="model.procedure" ta-toolbar="[[\'h1\',\'h2\'],[\'bold\',\'italics\',\'underline\'], [\'ul\', \'ol\'], [\'indent\', \'outdent\'], [\'insertLink\']]"></text-angular>',
'  </div>',
'</div>',
'<div class="row form-group">',
'  <div class="col-md-4">',
'    <h4>Cooking Time</h4>',
'    <textarea ng-model="model.cooking_time" rows="2" class="form-control"></textarea>',
'  </div>',
'  <div class="col-md-8">',
'    <h4>Materials</h4>',
'    <textarea ng-model="model.materials" rows="2" class="form-control"></textarea>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/star_rating.html', [
'',
'<input value="{{model}}" class="rating">',''].join("\n"));
}]);